---

- name: Allow the current user to run `sudo pacman` without a password
  hosts: manjaro
  become: true
  tasks:
    - name: Assure correct sudoers file
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/11-install-{{ lookup('env','USER') }}"
        line: "{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: true
        mode: 0600
        validate: 'visudo -cf %s'

- name: Install Base Packages
  hosts: manjaro
  roles:
    - base
  tags:
    - base

- name: Install Utility Packages
  hosts: manjaro
  roles:
    - utils
  tags:
    - utils
    - utilities

- name: Install Code Packages
  hosts: manjaro
  roles:
    - code
  tags:
    - code

- name: Install Cyber Packages
  hosts: manjaro
  roles:
    - cyber
  tags:
    - cyber

- name: Install Desktop Packages
  hosts: manjaro
  roles:
    - desktop
  tags:
    - desktop

- name: Install User Program Packages
  hosts: manjaro
  roles:
    - user-programs
  tags:
    - user-programs
