---

- name: Create Scripts directory
  file:
    path: "{{ scripts_dir }}"
    state: directory
    mode: 0777

- name: Clone git directory
  git:
    repo: https://github.com/Davincible/Manjaro-SystemdBoot-Integration
    dest: "{{ git_dir }}"
    version: master
