---

pacman_packages:
  - i3-gaps
  - dunst
  - dunstify
  - dunst-notify-speech
  - polybar
  - rofi
  - rofi-calc
  - xautolock
  - i3exit
  - i3lock

yay_packages:
  - rofi-autorandr
  - picom-ibhagwan-git
