---

pacman_packages:
  - baobab  # (Disk Usage Analyzer)
  - fd
  - nvtop   # (htop like monitoring for Nvidia GPUs)
  - tmux
  - kitty
  - jq
  - hq
  - yq
  - tree
  - lsd
  - bat    # cat alternative
  - procs  # ps alternative
  - sd     # sed alternative
  - dust   # du alternative
  - ripgrep  # grep alternative
  - tokei  # show statistics about code
  - hyperfine  # CLI benchmarking tool
  - tealdeer  # tldr alternative
  - bandwhich  # show network bandwith statistics
  - grex   # generate regex expressions from input
  - git-delta  # diff viewer
  - bat  # cat alternative
  - ripgrep-all
  - redshift
  - fzf
  - flameshot
  - gparted
  - kdeconnect
  - ranger
  - solaar
  - arandr
  - btrfs-progs
  - nvtop
  - gtop
  - ncdu    # (disk usage analyzer cli)
  - neofetch
  - rsync
  - snapper
  - spotifyd
  - youtube-dl

yay_packages:
  - xxd-standalone
  - insync
  - piavpn-bin
  - spotify-tui
  - tuxi-git
  - ytop-bin  # another top alternative
  - rmesg-git
