---

# - name: Install Base Packages
#   community.general.pacman:
#     name: neofetch
#     state: present

- name: Install Pacman Base Packages
  package:
    name: "{{ base_pacman_packages }}"
    state: present

- name: Install Yay Base Packages
  package:
    name: "{{ base_pacman_packages }}"
    state: present
