- include: install.yml
  become_method: sudo
  become: true
  become_user: root
    #   vars:
    #     ansible_password: "{{ primary_passwd }}"
    #     ansible_become_password: "{{ primary_passwd }}"
